plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
title: Awakening to Reality Practices
description: A collection of useful meditation techniques and contemplations for each stage of the Awakening to Reality map by John Tan and Soh Wei Yu. This is organised by stage, for ease of finding techniques that are suitable for your level.
theme: jekyll-theme-cayman